esphome:
  name: esp32c6-smoke-sensor
  friendly_name: "Smoking Room Smoke Sensor"
  on_boot:
    priority: -100
    then:
      - logger.log: "MQ2 sensor warming up for 60 seconds..."
      - delay: 60s
      - logger.log: "MQ2 sensor ready!"

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # WiFi settings compatible with BLE
  power_save_mode: light
  fast_connect: true
  reboot_timeout: 15min

  # Use manual IP to avoid DHCP issues
  manual_ip:
    static_ip: 192.168.86.200
    gateway: 192.168.86.1
    subnet: 255.255.255.0

  # Enable fallback hotspot
  ap:
    ssid: "ESP32C6-Smoke-Sensor"
    password: "smokedetector123"

# Captive portal for easy setup
captive_portal:

# Web server for diagnostics
web_server:
  port: 80

# BLE Tracker for scanning
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

# BLE Proxy for Home Assistant
bluetooth_proxy:
  active: true

# Sensors
sensor:
  # Uptime sensor
  - platform: uptime
    name: "Smoke Sensor Uptime"

  # WiFi signal strength
  - platform: wifi_signal
    name: "Smoke Sensor WiFi Signal"
    update_interval: 60s

# Binary sensor for MQ2 Digital output
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO8
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Smoke Detected"
    id: smoke_detected
    device_class: smoke
    filters:
      - delayed_on: 100ms
      - delayed_off: 2s

# Status LED (built-in on GPIO15 for ESP32-C6)
status_led:
  pin: GPIO15

# Optional: Button to manually restart
button:
  - platform: restart
    name: "Restart Smoke Sensor"
