esphome:
  name: esp32c6-smoke-sensor
  friendly_name: "Smoking Room Smoke Sensor"
  on_boot:
    priority: -100
    then:
      - logger.log: "MQ2 sensor warming up for 60 seconds..."
      - delay: 60s
      - logger.log: "MQ2 sensor ready!"

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: light
  fast_connect: true
  reboot_timeout: 15min

  manual_ip:
    static_ip: 192.168.86.200
    gateway: 192.168.86.1
    subnet: 255.255.255.0

  ap:
    ssid: "ESP32C6-Smoke-Sensor"
    password: "smokedetector123"

captive_portal:

web_server:
  port: 80

# BLE Tracker for scanning
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

# BLE Proxy for Home Assistant
bluetooth_proxy:
  active: true

# Sensors
sensor:
  # MQ2 Analog sensor - RAW reading so you can see it change
  - platform: adc
    pin: GPIO0
    name: "MQ2 Smoke Level"
    id: smoke_sensor
    update_interval: 500ms
    attenuation: 11db
    unit_of_measurement: "mV"
    accuracy_decimals: 0
    filters:
      - multiply: 1000  # Convert to millivolts for easier reading

  # Uptime sensor
  - platform: uptime
    name: "Smoke Sensor Uptime"

  # WiFi signal strength
  - platform: wifi_signal
    name: "Smoke Sensor WiFi Signal"
    update_interval: 60s

# Status LED
status_led:
  pin: GPIO15

# Restart button
button:
  - platform: restart
    name: "Restart Smoke Sensor"
